import logging
from enum import StrEnum
from typing import (
    Generic,
    Literal,
    Type,
    TypeVar,
)
from uuid import UUID

import sqlalchemy as sa
from sqlalchemy import CTE
from sqlalchemy.dialects.postgresql import insert as pg_insert
from sqlalchemy.ext.asyncio import AsyncSession
from sqlalchemy.orm import InstrumentedAttribute

from libs.cp_common.models.enum import SortOrder
from libs.cp_common.models.pydantic import (
    NoneValidationMixin,
    ViewListQueries,
)
from libs.cp_postgresql.models.pydantic.filters import (
    BaseFilter,
    FilterProtocol,
)
from libs.cp_postgresql.models.sqlalchemy import (
    OrmModel,
    SQLAlchemyBase,
)
from libs.cp_postgresql.postgresql import PostgreSQL


__all__ = ["BaseDatabaseGeneric"]


Table = TypeVar(name="Table", bound=SQLAlchemyBase)
Model = TypeVar(name="Model", bound=OrmModel)
ModelCreate = TypeVar(name="ModelCreate", bound=OrmModel)
ModelUpdate = TypeVar(name="ModelUpdate", bound=NoneValidationMixin)
Id = TypeVar(name="Id")
TFilterField = TypeVar("TFilterField", bound=StrEnum)


class BaseDatabaseGeneric(Generic[Table, Id, Model, ModelCreate, ModelUpdate]):
    """Generic asynchronous repository for typed SQLAlchemy persistence."""

    logger: logging.Logger
    database: PostgreSQL

    _table: Type[Table]
    _id: Type[Id]
    _model_create: Type[ModelCreate]
    _model_update: Type[ModelUpdate]
    _model: Type[Model]

    def __init__(self):
        """Initialize the repository logger."""

        self.logger = logging.getLogger(self.__class__.__name__)

    @property
    def table(self) -> Type[Table]:
        """Getter for the `_table` attribute."""
        return self._table

    @property
    def id(self) -> Type[Id]:
        """Getter for the `_id` attribute."""
        return self._id

    @property
    def model_create(self) -> Type[ModelCreate]:
        """Getter for the `_model_create` attribute."""
        return self._model_create

    @property
    def model_update(self) -> Type[ModelUpdate]:
        """Getter for the `_model_update` attribute."""
        return self._model_update

    @property
    def model(self) -> Type[Model]:
        """Getter for the `_model` attribute."""
        return self._model

    async def create(
        self,
        model: ModelCreate,
        session: AsyncSession | None = None,
        return_query: bool = False,
        mode: Literal["json", "python"] = "python",
    ) -> Model | CTE:
        """Create model in database.

        Args:
            model (ModelCreate): model with not DB-autogenerated fields
            session (AsyncSession, optional): SQLAlchemy AsyncSession for database interaction
            return_query (bool): if True return only query without execution
            mode (Literal["json", "python"]): model dump mode

        Returns:
            Model: created model
        """
        query = sa.insert(self._table).values(**model.model_dump(mode=mode)).returning(self._table)

        if return_query:
            return query.cte()

        if session:
            result = await session.execute(query)
        else:
            async with self.database.session() as session:
                result = await session.execute(query)
        created_model = result.fetchone()
        return self._model.model_validate(created_model)

    async def bulk_create(
        self,
        models: list[ModelCreate],
        session: AsyncSession | None = None,
        return_query: bool = False,
        mode: Literal["json", "python"] = "python",
    ) -> list[Model] | CTE:
        """Create models in database.

        Args:
            models (list[ModelCreate]): models with not DB-autogenerated fields
            session (AsyncSession, optional): SQLAlchemy AsyncSession for database interaction
            return_query (bool): if True return only query without execution
            mode (Literal["json", "python"]): model dump mode

        Returns:
            list[Model]: created models
        """
        if not models:
            return []
        query = sa.insert(self._table).values([model.model_dump(mode=mode) for model in models]).returning(self._table)

        if return_query:
            return query.cte()

        if session:
            result = await session.execute(query)
        else:
            async with self.database.session() as session:
                result = await session.execute(query)
        created_models = result.fetchall()
        return [self._model.model_validate(model) for model in created_models]

    async def get(
        self,
        id: Id | None = None,
        session: AsyncSession | None = None,
        return_query: bool = False,
        **filters,
    ) -> Model | None | CTE:
        """Get model by its ID and optional filter kwargs.

        Args:
            id (Id, optional): model ID
            session (AsyncSession, optional): SQLAlchemy AsyncSession for database interaction
            return_query (bool): if True return only query without execution

        Returns:
            Model | None: model if found, None otherwise
        """
        initial_clause = sa.and_(self._table.id == id) if id else None
        where_clause = self._apply_filters_to_clause(clause=initial_clause, **filters)
        query = sa.select(self._table).where(where_clause)

        if return_query:
            return query.cte()

        if session:
            result = await session.execute(query)
        else:
            async with self.database.session() as session:
                result = await session.execute(query)
        model = result.fetchone()
        if not model:
            return None
        return self._model.model_validate(model)

    async def get_by_ids(
        self, ids: list[Id], session: AsyncSession | None = None, return_query: bool = False, **filters
    ) -> list[Model] | CTE:
        """Get models by their IDs and optional filter kwargs.

        Args:
            ids (list[Id]): models IDs
            session (AsyncSession, optional): SQLAlchemy AsyncSession for database interaction
            return_query (bool): if True return only query without execution

        Returns:
            list[Model]: list of models
        """
        if not ids:
            return []
        initial_clause = sa.and_(self._table.id.in_(ids))
        where_clause = self._apply_filters_to_clause(clause=initial_clause, **filters)
        query = sa.select(self._table).where(where_clause)

        if return_query:
            return query.cte()

        if session:
            result = await session.execute(query)
        else:
            async with self.database.session() as session:
                result = await session.execute(query)
        models = result.fetchall()
        return [self._model.model_validate(model) for model in models]

    async def get_list(
        self,
        session: AsyncSession | None = None,
        return_query: bool = False,
        sort_by: str | list[str] | None = None,
        sort_order: SortOrder | str = SortOrder.ASC,
        **filters,
    ) -> list[Model] | CTE:
        """Get models by an optional filter kwargs.

        Args:
            session (AsyncSession, optional): SQLAlchemy AsyncSession for database interaction
            return_query (bool): if True return only query without execution
            sort_by (str | list[str] | None): field name or list of field names to sort by
            sort_order (SortOrder | str): sort direction for sort_by fields
            **filters: additional filtering parameters

        Returns:
            list[Model]: list of models
        """
        where_clause = self._apply_filters_to_clause(**filters)
        query = sa.select(self._table).where(where_clause)
        if sort_by:
            query = self.set_order_by_fields(query=query, sort_by=sort_by, sort_order=sort_order)

        if return_query:
            return query.cte()

        if session:
            result = await session.execute(query)
        else:
            async with self.database.session() as session:
                result = await session.execute(query)
        models = result.fetchall()
        return [self._model.model_validate(model) for model in models]

    async def get_paginated_list(
        self,
        queries: ViewListQueries,
        search_column: sa.Column | None = None,
        session: AsyncSession | None = None,
        filters_: list[BaseFilter] | None = None,
        filter_columns: dict[TFilterField, InstrumentedAttribute] | None = None,
        return_query: bool = False,
        **raw_filters,
    ) -> list[Model] | CTE:
        """Get a paginated list of models with optional search and filter kwargs.

        Args:
            queries (ViewListQueries): object containing pagination, sorting, and search parameters
            search_column (sa.Column | None): column to apply search filter on
            session (AsyncSession, optional): SQLAlchemy AsyncSession for database interaction
            filters_ (list[BaseFilter] | None): optional list of advanced filters, where each filter
                                                specifies a field, operator, and value
            filter_columns (dict[TFilterField, InstrumentedAttribute] | None): mapping from filter field enum values to
                                                                               SQLAlchemy columns. Used to apply filters_
                                                                               correctly to the query
            return_query (bool): if True return only query without execution
            **raw_filters: additional filtering parameters

        Returns:
            list[Model]: list of models matching the filters, search, and pagination criteria
        """
        where_clause = self._apply_filters_to_clause(**raw_filters)
        query = sa.select(self._table).where(where_clause)

        if filters_ and filter_columns:
            query = self.apply_filters(query=query, filters=filters_, filter_columns=filter_columns)

        if search_column and queries.search:
            query = self.set_search_by_column(query=query, search=queries.search, column=search_column)
        query = self.set_order_by(query=query, sort_by=queries.sort_by, sort_order=queries.sort_order)
        query = self.set_offset_limit(query=query, offset=queries.offset, limit=queries.limit)

        if return_query:
            return query.cte()

        if session:
            result = await session.execute(query)
        else:
            async with self.database.session() as session:
                result = await session.execute(query)
        models = result.fetchall()

        return [self._model.model_validate(model) for model in models]

    async def get_count(
        self,
        search: str | None = None,
        search_column: sa.Column | None = None,
        filters_: list[BaseFilter] | None = None,
        filter_columns: dict[TFilterField, InstrumentedAttribute] | None = None,
        session: AsyncSession | None = None,
        return_query: bool = False,
        **raw_filters,
    ) -> int | CTE:
        """Get rows count with optional search by column and filter kwargs.

        Args:
            search (str | None, optional): substring to search in column. Defaults to None.
            search_column (sa.Column | None, optional): column to search in. Defaults to None.
            filters_ (list[BaseFilter] | None): optional list of advanced filters, where each filter
                                                specifies a field, operator, and value.
            filter_columns (dict[TFilterField, InstrumentedAttribute] | None): mapping from filter field enum values to
                                                                               SQLAlchemy columns. Used to apply filters_
                                                                               correctly to the query
            session (AsyncSession, optional): SQLAlchemy AsyncSession for database interaction
            return_query (bool): if True return only query without execution

        Returns:
            int: rows count
        """
        where_clause = self._apply_filters_to_clause(**raw_filters)
        query = sa.select(sa.func.count()).select_from(self._table).where(where_clause)

        if filters_ and filter_columns:
            query = self.apply_filters(query=query, filters=filters_, filter_columns=filter_columns)

        if search and search_column:
            query = self.set_search_by_column(query=query, search=search, column=search_column)

        if return_query:
            return query.cte()

        if session:
            result = await session.execute(query)
        else:
            async with self.database.session() as session:
                result = await session.execute(query)
        return result.scalar()

    async def update(
        self,
        id: Id,
        data: ModelUpdate,
        updated_by_id: UUID | None = None,
        session: AsyncSession | None = None,
        return_query: bool = False,
        mode: Literal["json", "python"] = "python",
        **filters,
    ) -> Model | None | CTE:
        """Update model by its ID and optional filter kwargs.

        Args:
            id (Id): model ID
            data (ModelUpdate): data to update in model
            updated_by_id (UUID | None, optional): user ID who performed the update. Defaults to None.
            session (AsyncSession, optional): SQLAlchemy AsyncSession for database interaction
            return_query (bool): if True return only query without execution
            mode (Literal["json", "python"]): model dump mode

        Returns:
            Model | None: updated model if found and update, None otherwise
        """
        initial_clause = sa.and_(self._table.id == id)
        where_clause = self._apply_filters_to_clause(clause=initial_clause, **filters)
        update_data = data.model_dump(mode=mode, exclude_unset=True)
        if not update_data:
            return await self.get(id=id, **filters)
        if updated_by_id:
            update_data["updated_by_id"] = updated_by_id
        query = sa.update(self._table).where(where_clause).values(**update_data).returning(self._table)

        if return_query:
            return query.cte()

        if session:
            result = await session.execute(query)
        else:
            async with self.database.session() as session:
                result = await session.execute(query)
        model = result.fetchone()
        if not model:
            return None
        return self._model.model_validate(model)

    async def bulk_update(
        self,
        ids: list[UUID],
        data: ModelUpdate,
        session: AsyncSession | None = None,
        updated_by_id: UUID | None = None,
        return_query: bool = False,
        mode: Literal["json", "python"] = "python",
        **filters,
    ) -> list[Model] | CTE:
        """Update the models by IDs and optional filter kwargs.

        Args:
            ids (list[UUID]): model IDs
            data (ModelUpdate): data to update in models
            updated_by_id (UUID | None, optional): user ID who performed the update. Defaults to None.
            session (AsyncSession, optional): SQLAlchemy AsyncSession for database interaction
            return_query (bool): if True return only query without execution
            mode (Literal["json", "python"]): model dump mode

        Returns:
            list[Model]: updated models
        """
        if not ids:
            return []
        initial_clause = sa.and_(self._table.id.in_(ids))
        where_clause = self._apply_filters_to_clause(clause=initial_clause, **filters)
        update_data = data.model_dump(mode=mode, exclude_unset=True)
        if not update_data:
            return await self.get_by_ids(ids=ids, **filters)
        if updated_by_id:
            update_data["updated_by_id"] = updated_by_id
        query = sa.update(self._table).where(where_clause).values(**update_data).returning(self._table)

        if return_query:
            return query.cte()

        if session:
            result = await session.execute(query)
        else:
            async with self.database.session() as session:
                result = await session.execute(query)
        models = result.fetchall()
        return [self._model.model_validate(model) for model in models]

    async def upsert(
        self,
        data: ModelCreate,
        update_fields: set[str] | None = None,
        session: AsyncSession | None = None,
        conflict_fields: set[str] | None = None,
        return_query: bool = False,
        mode: Literal["json", "python"] = "python",
        on_conflict: Literal["update", "nothing"] = "update",
    ) -> Model | None | CTE:
        """
        Insert a record into the database or update it if a conflict occurs.

        Args:
            data (ModelCreate): data to insert into the table
            update_fields (set[str], optional): fields to update if a conflict occurs.
                If not provided, all fields except conflict fields will be updated
            session (AsyncSession, optional): SQLAlchemy AsyncSession for database interaction
            conflict_fields (set[str], optional): fields that trigger conflict detection (default: {"id"})
            return_query (bool): if True return only query without execution
            mode (Literal["json", "python"]): model dump mode
            on_conflict (Literal["update", "nothing"]): action on conflict (default: "update")

        Returns:
            Model | None: inserted or updated model instance, or None if no data was provided.
        """
        create_dict = data.model_dump(mode=mode)

        if not create_dict:
            return None

        conflict_fields = conflict_fields or ["id"]
        if update_fields is None:
            update_fields = [key for key in create_dict.keys() if key not in conflict_fields]

        insert_stmt = pg_insert(self._table).values(**create_dict)

        if on_conflict == "update":
            query = insert_stmt.on_conflict_do_update(
                index_elements=[getattr(self._table, field) for field in conflict_fields],
                set_={
                    field: getattr(insert_stmt.excluded, field)
                    for field in update_fields
                    if field not in conflict_fields
                },
            ).returning(self._table)
        elif on_conflict == "nothing":
            query = insert_stmt.on_conflict_do_nothing(
                index_elements=[getattr(self._table, field) for field in conflict_fields]
            ).returning(self._table)
        else:
            raise ValueError(f"Unknown on_conflict action: {on_conflict}")

        if return_query:
            return query.cte()

        if session:
            result = await session.execute(query)
        else:
            async with self.database.session() as session:
                result = await session.execute(query)

        model = result.fetchone()
        if model is None:
            return None
        return self._model.model_validate(model)

    async def bulk_upsert(
        self,
        data: list[ModelCreate],
        conflict_fields: set[str] | None = None,
        update_fields: set[str] | None = None,
        session: AsyncSession | None = None,
        return_query: bool = False,
        mode: Literal["json", "python"] = "python",
        on_conflict: Literal["update", "nothing"] = "update",
    ) -> list[Model] | CTE:
        """
        Bulk insert multiple records into the database or update them if conflicts occur.

        Args:
            data (list[ModelCreate]): list of data objects to insert
            conflict_fields (set[str], optional): fields that trigger conflict detection (default: {"id"})
            update_fields (set[str], optional): fields to update if a conflict occurs.
                If not provided, all fields except conflict fields will be updated
            session (AsyncSession, optional): SQLAlchemy AsyncSession for database interaction
            return_query (bool): if True return only query without execution
            mode (Literal["json", "python"]): model dump mode
            on_conflict (Literal["update", "nothing"]): action on conflict (default: "update")

        Returns:
            list[Model]: list of inserted or updated model instances.
        """
        if not data:
            return []

        models_data = [m.model_dump(mode=mode) for m in data]
        if not models_data:
            return []

        conflict_fields = conflict_fields or ["id"]
        if update_fields is None:
            update_fields = [key for key in models_data[0].keys() if key not in conflict_fields]

        insert_stmt = pg_insert(self._table).values(models_data)

        if on_conflict == "update":
            query = insert_stmt.on_conflict_do_update(
                index_elements=[getattr(self._table, field) for field in conflict_fields],
                set_={
                    field: getattr(insert_stmt.excluded, field)
                    for field in update_fields
                    if field not in conflict_fields
                },
            ).returning(self._table)
        elif on_conflict == "nothing":
            query = insert_stmt.on_conflict_do_nothing(
                index_elements=[getattr(self._table, field) for field in conflict_fields]
            ).returning(self._table)
        else:
            raise ValueError(f"Unknown on_conflict action: {on_conflict}")

        if return_query:
            return query.cte()

        if session:
            result = await session.execute(query)
        else:
            async with self.database.session() as session:
                result = await session.execute(query)
        models = result.fetchall()

        return [self._model.model_validate(model) for model in models]

    async def delete(
        self, id: Id, session: AsyncSession | None = None, return_query: bool = False, **filters
    ) -> Model | None | CTE:
        """Delete model by its ID and optional filter kwargs.

        Args:
            id (Id): model ID
            session (AsyncSession, optional): SQLAlchemy AsyncSession for database interaction
            return_query (bool): if True return only query without execution

        Returns:
            Model | None: deleted model if found, None otherwise
        """
        initial_clause = sa.and_(self._table.id == id)
        where_clause = self._apply_filters_to_clause(clause=initial_clause, **filters)
        query = sa.delete(self._table).where(where_clause).returning(self._table)

        if return_query:
            return query.cte()

        if session:
            result = await session.execute(query)
        else:
            async with self.database.session() as session:
                result = await session.execute(query)
        model = result.fetchone()
        if model is None:
            return None
        return self._model.model_validate(model)

    async def delete_many(
        self, ids: list[Id], session: AsyncSession | None = None, return_query: bool = False, **filters
    ) -> list[Model] | CTE:
        """Delete models by their IDs and optional filter kwargs.

        Args:
            ids (list[Id]): list of models IDs
            session (AsyncSession, optional): SQLAlchemy AsyncSession for database interaction
            return_query (bool): if True return only query without execution

        Returns:
            list[Model]: list of deleted models
        """
        if not ids:
            return []
        initial_clause = sa.and_(self._table.id.in_(ids))
        where_clause = self._apply_filters_to_clause(clause=initial_clause, **filters)
        query = sa.delete(self._table).where(where_clause).returning(self._table)

        if return_query:
            return query.cte()

        if session:
            result = await session.execute(query)
        else:
            async with self.database.session() as session:
                result = await session.execute(query)
        models = result.fetchall()
        return [self._model.model_validate(model) for model in models]

    async def delete_list(
        self, session: AsyncSession | None = None, return_query: bool = False, **filters
    ) -> list[Model] | CTE:
        """Delete models by an optional filter kwargs.

        Args:
            session (AsyncSession, optional): SQLAlchemy AsyncSession for database interaction
            return_query (bool): if True return only query without execution

        Returns:
            list[Model]: list of models
        """
        where_clause = self._apply_filters_to_clause(**filters)
        query = sa.delete(self._table).where(where_clause).returning(self._table)

        if return_query:
            return query.cte()

        if session:
            result = await session.execute(query)
        else:
            async with self.database.session() as session:
                result = await session.execute(query)
        models = result.fetchall()
        return [self._model.model_validate(model) for model in models]

    async def truncate(self, session: AsyncSession | None = None, return_query: bool = False) -> None | CTE:
        """Delete all records from the table.

        Args:
            session (AsyncSession, optional): SQLAlchemy AsyncSession for database interaction
            return_query (bool): if True return only query without execution
        """
        query = sa.delete(self._table)

        if return_query:
            return query.cte()

        if session:
            await session.execute(query)
        else:
            async with self.database.session() as session:
                await session.execute(query)

    def _apply_filters_to_clause(self, clause: sa.ColumnElement | None = None, **filters) -> sa.ColumnElement:
        """Apply filters to clause.

        Args:
            clause (sa.ColumnElement | None, optional): initial clause. Defaults to None.

        Returns:
            sa.ColumnElement: clause with applied filters
        """
        if clause is None:
            clause = sa.and_()
        for field, value in filters.items():
            table_field = getattr(self._table, field, None)
            if table_field is None:
                raise ValueError(f"Unknown filter field '{field}' for {self._table.__tablename__}")

            if isinstance(value, list):
                clause &= table_field.in_(value)
            else:
                clause &= table_field == value
        return clause

    @staticmethod
    def set_search_by_column(query: sa.Select, search: str, column: sa.Column) -> sa.Select:
        """
        Setting 'search' variable value as searching by getting SQLAlchemy 'column'.

        Args:
            query: collected user select(...).where(...).
            search: what should be searched for by the selected 'column' in the database.
            column: SQLAlchemy column for searching 'search' inside.
        Returns:
            sa.Select: updated select(...).where(...).where(column.icontains(search)).
        """

        search = search.strip().lower()
        if len(search) != 0:
            query = query.where(column.icontains(search))
        return query

    @staticmethod
    def set_search_by_columns(query: sa.Select, search: str, columns: list[sa.Column]) -> sa.Select:
        """
        Setting 'search' variable value as searching by getting SQLAlchemy 'column'.

        Args:
            query: collected user select(...).where(...).
            search: what should be searched for by the selected 'column' in the database.
            columns: SQLAlchemy columns for searching 'search' inside.
        Returns:
            sa.Select: updated select(...).where(...).where(or_(column.icontains(search), ...)).
        """

        search = search.strip().lower()

        if not search or not columns:
            return query

        conditions = [column.icontains(search) for column in columns]
        query = query.where(sa.or_(*conditions))

        return query

    @staticmethod
    def set_offset_limit(query: sa.Select, offset: int, limit: int) -> sa.Select:
        """
        Setting 'offset' and 'limit' for collected user select(...).where(...).

        Args:
            query: collected user select(...).where(...).
            offset: used to skip rows before returning a result of the query.
            limit: number of rows returned by the query.
        Returns:
            sa.Select: updated select(...).where(...).offset(offset).limit(limit).
        """

        return query.offset(offset).limit(limit)

    @staticmethod
    def set_order_by(query: sa.Select, sort_by: str, sort_order: SortOrder) -> sa.Select:
        """
        Setting 'order_by' with 'asc' and 'desc' options for collected user select(...).where(...).

        Args:
            query: collected user select(...).where(...).
            sort_by: sorting column in database.
            sort_order: option to sort rows in 'sort_order.ASC' or in 'sort_order.DESC' order.
        Returns:
            sa.Select: updated select(...).where(...).order_by("column asc").
        """

        sort_by = sort_by.strip().lower()
        sort_order = sort_order.strip().lower()
        query = query.order_by(sa.text(f"{sort_by} {sort_order}"))
        return query

    def set_order_by_fields(
        self,
        query: sa.Select,
        sort_by: str | list[str],
        sort_order: SortOrder | str = SortOrder.ASC,
    ) -> sa.Select:
        """Set order_by using validated table field names."""

        sort_fields = [sort_by] if isinstance(sort_by, str) else sort_by
        sort_order = SortOrder(sort_order.strip().lower())
        order_clauses = []
        for field in sort_fields:
            field = field.strip().lower()
            table_field = getattr(self._table, field, None)
            if table_field is None:
                raise ValueError(f"Unknown sort field '{field}' for {self._table.__tablename__}")

            if sort_order == SortOrder.DESC:
                order_clauses.append(table_field.desc())
            else:
                order_clauses.append(table_field.asc())

        if order_clauses:
            query = query.order_by(*order_clauses)
        return query

    def apply_filters(
        self,
        query: sa.Select | sa.Subquery,
        filters: list[BaseFilter],
        filter_columns: dict,
    ) -> sa.Select:
        """Apply typed filters to their configured SQLAlchemy columns.

        Args:
            query: Query to filter.
            filters: Filter models to apply in order.
            filter_columns: Mapping from public filter fields to columns.

        Returns:
            The filtered query.
        """
        for filter_ in filters:
            column = filter_columns[filter_.field]
            query = self._apply_filter(query=query, column=column, filter=filter_)
        return query

    @staticmethod
    def _apply_filter(query: sa.Select | sa.Subquery, column: sa.Column, filter: FilterProtocol) -> sa.Select:
        """Delegate one query transformation to a filter implementation."""

        query = filter.q(query=query, column=column)
        return query
