services:
  minio:
    restart: unless-stopped
    env_file: [minio.env]
    image: pgsty/minio:RELEASE.2026-06-18T00-00-00Z
    command: server /data --console-address ":9001"
    volumes:
      - /data/minio/data:/data
    labels:
      - prometheus.io/scrape=true
      - prometheus.io/port=9000
      - prometheus.io/path=/minio/v2/metrics/cluster
      - traefik.enable=true
      - traefik.http.services.${ENV_NAME:-}-minio-gui.loadbalancer.server.port=9001
      - traefik.http.routers.${ENV_NAME:-}-minio-gui.service=${ENV_NAME:-}-minio-gui
      - traefik.http.routers.${ENV_NAME:-}-minio-gui.rule=Host(`${APP_HOST:-localhost}`) && PathPrefix(`/minio/`)
      - traefik.http.middlewares.${ENV_NAME:-}-minio-gui-stripprefix.stripprefix.prefixes=/minio
      - traefik.http.routers.${ENV_NAME:-}-minio-gui.middlewares=${ENV_NAME:-}-minio-gui-stripprefix
