services:
  redisinsight:
    restart: unless-stopped
    image: redis/redisinsight:3.4
    depends_on: { volume-init: { condition: service_completed_successfully } }
    environment:
      RI_PROXY_PATH: /redisinsight/
    volumes:
      - /data/redisinsight/data:/data
    labels:
      - traefik.enable=true
      - traefik.http.services.${ENV_NAME:-}-redisinsight.loadbalancer.server.port=5540
      - traefik.http.routers.${ENV_NAME:-}-redisinsight.service=${ENV_NAME:-}-redisinsight
      - traefik.http.routers.${ENV_NAME:-}-redisinsight.rule=Host(`${APP_HOST:-localhost}`) && PathPrefix(`/redisinsight`)
      - traefik.http.routers.${ENV_NAME:-}-redisinsight.middlewares=auth@file
