services:
  oauth2-proxy:
    restart: unless-stopped
    image: bitnamilegacy/oauth2-proxy:7.9.0
    entrypoint: [oauth2-proxy]
    depends_on: { keycloak: { condition: service_healthy } }
    command: [--config=/oauth2-proxy.cfg]
    volumes:
      - ./oauth2-proxy.cfg:/oauth2-proxy.cfg:ro
    labels:
      - traefik.enable=true
      - traefik.http.services.ncn-oauth2-proxy.loadbalancer.server.port=4180
      - traefik.http.routers.ncn-oauth2-proxy.service=ncn-oauth2-proxy
      - traefik.http.routers.ncn-oauth2-proxy.rule=Host(`${APP_HOST:-localhost}`) && PathPrefix(`/oauth2`)
      - traefik.http.routers.ncn-oauth2-proxy.entrypoints=http
      - traefik.http.middlewares.oauth2-signin.errors.service=ncn-oauth2-proxy
      - traefik.http.middlewares.oauth2-signin.errors.status=401
      - traefik.http.middlewares.oauth2-signin.errors.query=/oauth2/sign_in?rd={url}
      - traefik.http.middlewares.oauth2-verify.forwardAuth.address=http://${APP_HOST:-localhost}/oauth2/auth
      - traefik.http.middlewares.oauth2-verify.forwardAuth.trustForwardHeader=true
      - traefik.http.middlewares.oauth2-verify.forwardAuth.tls.insecureSkipVerify=true
      - traefik.http.middlewares.oauth2-verify.forwardAuth.authResponseHeaders=X-Auth-Request-Email,X-Auth-Request-Preferred-,X-Auth-Request-Access-Token,X-Auth-Request-Roles,X-Auth-Request-User,X-Forwarded-Groups,Authorization,X-Auth-Request-Groups
